-
  name: 'Asset directory paginate'
  uriPattern: '{node}/documents-page/{--asset-directory-pagination.currentPage}.html'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    '@format': 'html'
    '--asset-directory-pagination':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      'currentPage': '1'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

