TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Shel.MediaFrontend': TRUE
  TypoScript:
    defaultContext:
      MediaFrontend: 'Shel\MediaFrontend\Eel\Helper\MediaFrontendHelper'

Shel:
  MediaFrontend:
    assetDirectory:
      pagination:
        itemsPerPage: 6
        maximumNumberOfLinks: 10
