
Shel:
  MediaFrontend:
    assetDirectory:
      pagination:
        itemsPerPage: 6
        maximumNumberOfLinks: 10
Neos:
  Flow:
    mvc:
      routes:
        Shel.MediaFrontend:
          position: 'before Neos.Neos'
  Neos:
    nodeTypes:
      groups:
        shelMediaFrontend:
          label: 'Media frontend'
    fusion:
      autoInclude:
        Shel.MediaFrontend: true
  Fusion:
    defaultContext:
      MediaFrontend: Shel\MediaFrontend\Eel\Helper\MediaFrontendHelper
