
Shel:
  MediaFrontend:
    assetDirectory:
      pagination:
        itemsPerPage: 6
        maximumNumberOfLinks: 10
Neos:
  Neos:
    typoScript:
      autoInclude:
        Shel.MediaFrontend: true
    nodeTypes:
      groups:
        shelMediaFrontend:
          label: 'Media frontend'
  Fusion:
    defaultContext:
      MediaFrontend: Shel\MediaFrontend\Eel\Helper\MediaFrontendHelper
